# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Prokea\Bundle\AuthenticationBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: ProkeaShopRuleBundle:User
                property: username

    firewalls:
        user_registration:
            pattern:   ^/register$
            anonymous: ~
            
        shop_login: 
            pattern:   ^/login$
            anonymous: ~
            
        secured_area:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /authorize/login_check
            provider:       db_provider
            
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
#        shop_login:
#            pattern:                ^login$
#            anonymous:              ~
#
#        shop_authorize:
#            pattern:                ^/authorize
#            remember_me:
#                secret:             "%kernel.secret%"
#            form_login:
#                login_path:         /login
#                check_path:         /authorize/login_check
##            logout:
##                path:               /authorize/logout
##                target:             /
#            provider:               default
#            
#        api_oauth2_authorize:
#            pattern:                ^/api/oauth2/authorize$
#            http_basic:             ~
#            provider:               default
#
#        api_oauth2_token:
#            pattern:                ^/api/oauth2/token$
#            oauth2_token:           ~
#            
#        api_oauth2_debug:
#            pattern:                ^/api/oauth2/debug$
#            oauth2_resource:        ~
#        
#        api_resource_model:
#            pattern:                ^/api/resource/model$
#            oauth2_resource:
#                resource_type:      model
#                scope:              [ demoscope1 ]
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
