<?php
namespace Prokea\Bundle\AuthenticationBundle\Entity;

use AuthBucket\OAuth2\Model\AccessTokenManagerInterface;

/**
 * AccessTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessTokenRepository extends AbstractEntityRepository implements AccessTokenManagerInterface
{
}
