<?php
namespace Prokea\Bundle\AuthenticationBundle\Entity;

use AuthBucket\OAuth2\Model\AuthorizeManagerInterface;

/**
 * AuthorizeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizeRepository extends AbstractEntityRepository implements AuthorizeManagerInterface
{
}
