<?php
namespace Prokea\Bundle\AuthenticationBundle\Entity;

use AuthBucket\OAuth2\Model\ScopeManagerInterface;

/**
 * ScopeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScopeRepository extends AbstractEntityRepository implements ScopeManagerInterface
{
}
