user_registration:
    path:       /register
    defaults:   { _controller: ProkeaAuthenticationBundle:Registration:register }
    methods:    [ GET|POST ]
shop_login:
    path:       /login
    defaults:   { _controller: ProkeaAuthenticationBundle:Login:login }
    methods:    [ GET ]
login_check:
    path:       /login_check
    methods:    [ GET|POST ]
logout:
    path:       /logout
authorize:
    path:       /oauth/authorize
    defaults:   { _controller: ProkeaAuthenticationBundle:Authentication:authorize }
    methods:    [ GET|POST ]
request_code:
    path:       /oauth/request/code
    defaults:   { _controller: ProkeaAuthenticationBundle:Authentication:requestCode }
    methods:    [ GET ]
demo_response_type_code:
    path:       /oauth/response_type/code
    defaults:   { _controller: ProkeaAuthenticationBundle:Authentication:responseTypeCode }
    methods:    [ GET ]
demo_grant_type_authorization_code:
    path:       /oauth/grant_type/authorization_code
    defaults:   { _controller: ProkeaAuthenticationBundle:Authentication:grantTypeAuthorizationCode }
    methods:    [ GET ]
